version: "3.8"

services:
  booking-hotel-service:
    container_name: booking-hotel-container
    build: .
    image: booking-hotel-image
    volumes:
      - ./:/app
    ports:
      - "8001:8001"


  jenkins-service:
    container_name: jenkins-container
    build: ./jenkins
    image: jenkins-image
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - booking-hotel-service

volumes:
  jenkins_home: